"""Agente: cliente LLM abstraído (``LLMClient``), fake para testes e laço de *tool calling*.

O orquestrador + verificador HITL fica em ``bdgd_light.agent.orquestrador`` e não é reexportado
aqui de propósito: ele depende de ``bdgd_light.mcp_server.sessao``, que por sua vez usa
``bdgd_light.agent.audit`` — importar aqui fecharia um ciclo.
"""

from bdgd_light.agent.audit import GENESIS, AuditError, AuditLog, Registro
from bdgd_light.agent.llm import (
    ENV_ENDPOINT,
    ENV_GEMINI_KEY,
    ENV_GITHUB_TOKEN,
    ENV_MODELO,
    ENV_OPENAI_KEY,
    ENV_PROVIDER,
    ENV_TOKEN,
    PERFIS,
    PROVEDOR_PADRAO,
    SOMA,
    Conversa,
    FakeLLMClient,
    Ferramenta,
    GitHubModelsClient,
    LimiteDeTaxaError,
    LLMClient,
    LLMError,
    Message,
    OpenAICompatClient,
    Perfil,
    Resposta,
    RespostaInvalidaError,
    RespostaVaziaError,
    ServicoIndisponivelError,
    Text,
    TokenAusenteError,
    ToolCall,
    ToolCalls,
    ToolSpec,
    Uso,
    cliente_do_ambiente,
    cliente_por_perfil,
    conversar,
    descrever_cliente,
    fake_soma,
    interpretar_resposta,
    registrar_cliente,
    soma,
)

__all__ = [
    "GENESIS",
    "AuditError",
    "AuditLog",
    "Registro",
    "ENV_ENDPOINT",
    "ENV_GEMINI_KEY",
    "ENV_GITHUB_TOKEN",
    "ENV_MODELO",
    "ENV_OPENAI_KEY",
    "ENV_PROVIDER",
    "ENV_TOKEN",
    "PERFIS",
    "PROVEDOR_PADRAO",
    "SOMA",
    "Conversa",
    "FakeLLMClient",
    "Ferramenta",
    "GitHubModelsClient",
    "LLMClient",
    "LLMError",
    "LimiteDeTaxaError",
    "Message",
    "OpenAICompatClient",
    "Perfil",
    "Resposta",
    "RespostaInvalidaError",
    "RespostaVaziaError",
    "ServicoIndisponivelError",
    "Text",
    "TokenAusenteError",
    "ToolCall",
    "ToolCalls",
    "ToolSpec",
    "Uso",
    "cliente_do_ambiente",
    "cliente_por_perfil",
    "conversar",
    "descrever_cliente",
    "fake_soma",
    "interpretar_resposta",
    "registrar_cliente",
    "soma",
]
